# -*- coding: utf-8 -*-
"""AllWays_Ottawa_GPS.ipynb

Automatically generated by Colab.

# 🗺️ AllWays Ottawa
Run the cell below to launch the app in demo mode inside a phone frame.

To connect to the full backend (PostGIS scoring + real AI), run the Flask
server locally and update API_BASE in the HTML below to point to your server.

## Architecture
| Mode | How it works |
|---|---|
| **Demo** (Colab / standalone) | Client-side OSRM + hardcoded Allen responses |
| **Connected** (with backend) | Flask API + PostGIS scoring + OpenAI Allen |

The frontend auto-detects which mode to use on page load.
"""

from IPython.display import display, HTML
import os

# ── Load the frontend HTML ──────────────────────────────
# If running from the repo, load the shared frontend/index.html
# Otherwise, use the embedded version below.
frontend_path = os.path.join(os.path.dirname(__file__) if '__file__' in dir() else '.', 
                              'frontend', 'index.html')

if os.path.exists(frontend_path):
    with open(frontend_path, 'r', encoding='utf-8') as f:
        html = f.read()
    print("✅ Loaded frontend from frontend/index.html")
else:
    # Standalone mode: fetch from GitHub raw (update URL to your repo)
    # Or use the embedded fallback
    print("ℹ️  Running in standalone Colab mode (demo only)")
    print("   For full features, clone the repo and run the Flask backend.")
    
    # Embedded minimal launcher that loads from CDN or shows instructions
    html = r'''
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1.0"/>
<title>AllWays Ottawa — Colab Launcher</title>
<style>
  body { background: #181820; color: #e8e8f0; font-family: 'Segoe UI', system-ui, sans-serif; 
         display: flex; align-items: center; justify-content: center; min-height: 100vh; margin: 0; }
  .card { background: #222230; border: 1px solid #3a3a50; border-radius: 16px; padding: 32px;
          max-width: 480px; text-align: center; }
  h1 { font-size: 1.4rem; margin-bottom: 12px; }
  h1 em { color: #4ab3e8; font-style: normal; }
  p { color: #7a7a9a; font-size: 0.9rem; line-height: 1.6; margin-bottom: 16px; }
  code { background: #28283a; padding: 2px 8px; border-radius: 6px; font-size: 0.82rem; color: #5dd87a; }
  .steps { text-align: left; background: #28283a; border-radius: 12px; padding: 16px 20px; 
           font-family: monospace; font-size: 0.8rem; color: #e8e8f0; line-height: 1.8; }
  .steps .cmd { color: #4ab3e8; }
</style>
</head>
<body>
<div class="card">
  <h1>All<em>Ways</em> Ottawa</h1>
  <p>The frontend file wasn't found alongside this notebook.<br>
     To run the full app, clone the repository:</p>
  <div class="steps">
    <span class="cmd">git clone</span> https://github.com/YOUR-USER/allways-ottawa.git<br>
    <span class="cmd">cd</span> allways-ottawa<br>
    <span class="cmd">bash</span> setup.sh<br>
    <span class="cmd">cd</span> backend && python app.py<br>
    <br>
    Then open <span class="cmd">http://localhost:5001</span>
  </div>
  <p style="margin-top:16px;">Or just open <code>frontend/index.html</code> in any browser for demo mode.</p>
</div>
</body>
</html>
'''

display(HTML(html))

"""---
## Pages
| Tab | Page |
|---|---|
| 🏠 Home | Overview of the 3 route types |
| 🗺️ Map | Enter locations, view colour-coded routes |
| 🤖 Allen | AI assistant — or tap the FAB button on the map |
| ❓ Feedback | Full feedback form with star rating |

## Running the Full Backend

```bash
# 1. Clone the repo
git clone https://github.com/YOUR-USERNAME/allways-ottawa.git
cd allways-ottawa

# 2. One-command setup (starts DB, loads data)
bash setup.sh

# 3. Start the server
cd backend && source venv/bin/activate && python app.py

# 4. Open http://localhost:5001
# The mode badge will show "CONNECTED" in green
```
"""
